<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task 04</title>
</head>

<body>
    <script>
        /*
        Задание:
        Создайте пользовательский класс исключения DivideByZeroError
        Сделайте так, чтобы функция divide при попытке деления на 0 выбрасывала эту ошибку.
        Добавьте код, обрабатывающий исключение.
        */

        class DivideByZeroError extends Error {
            constructor(argumentName) {
                super(`Аргумент с именем ${argumentName} содержит значение 0.`);
                this.name = "Деление на ноль";
            }

        }

        function divide(operand1, operand2) {
            if (operand2 === 0) throw new DivideByZeroError("operand2");
            return operand1 / operand2;
        }

        try {
            console.log(divide(10, 5));
            console.log(divide(100, 0));
            console.log(divide(1000, 50));
        } catch (error) {
            console.log(error.message);
        }
    </script>
</body>

</html>